[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "6aa12de5dc31934066812d7333b1092a85b2a2c6"
os = "macos"

    [[DuckDB.download]]
    sha256 = "cc1c901e369372313e6562bbcc2c64014f055d30f4b692c3c1689d3206f3bd15"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "194b82bfd84b1f1ae0e6bbc4febe6985d2b0882a"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "ddb64dadffd6ca88c6bc5ad9c459b002235330aa58a6085257fee3f856080705"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23b01b5f6bec918fa4a456195a92ab29dc33cf8b"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "a82f579bc2b05cffa4037df8f719e3e6e43ce33706736f633eb563025d03f3f8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "28f2da1936b29e1f1c97872d422eb6f0230ff5bc"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "ec297f3418ef5d7a2f14c446406c82d9dd00c0bd8222fcd6998c6a3f47bac580"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25d3ebe54d6f22144f4b138fe334747f5ba012d5"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "346da49e67eee89f8b3bed75b705f9fe1c800a8ac97be8af48c22d3c21ab9909"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2826e1418ea7b66c7dd631c51e128b89accf9cdd"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "611235c2156a80b2edebd3a998f0417e04e4ddee1c0d7368b8cb16d94914889d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a7bf18687eda8eab7495de27931a1ce3389dabf"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "b5737398038aa7bff85733700ea29e2db56daae1d674009eef67b760f50b99c8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b411513acc8a4312878f35da7f787e4f95456ebd"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "5de0ac850c31be15a688de7e21ad222668c4acc3c30cb82ddaf6336381bad81a"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4879b3a6947607c6416cf853d3d60079329fd3de"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "45cfea7236fa3147a7d7fc780cd640c9bf61cc78526e75fe5d353624a4b51620"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1332026d5ce7dbe7ac9ce7dfe5a17a0576d11729"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "27faabc7f69ca63887cabe2485c3772b6b82c5f94ed52cd9f61823b0cd3c2893"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77835ff842b1c1351d866bb110b2431177dc90c7"
os = "windows"

    [[DuckDB.download]]
    sha256 = "b2c3d46d0848eba935e27efd320954e5b3ff773fb6d1a2580617dd99ea603b6f"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b384b52d4ba02d786bd2ab5ca903e2cd25db0f97"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "54e3a32f038e74cde04603a72b5f3b4e4ffc75645e39072343916e204ba5c397"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "8937cc72ca7a6605622ea8a634597e721985bcee"
os = "macos"

    [[DuckDB.download]]
    sha256 = "9894ff84d90a2542100dfde9732d15286d8471d827209c2d0ddc100c84341688"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b95d65b08cf0146ed9ff92f99b046a17ba9a397c"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "609d7a29bfbc273d8dd6f682db7d898e2123743f0243ce6845ea856667974d23"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d13a6f7c161055b71546678150afac825fc757bf"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "d4e2c803e971486f1bebf47a1c60e61d46861d079140a9b3dc11202a254b214a"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "e3d29a0f404a6b35e5bd3f5ffc92c95d303f7117"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "e2421d4f707d109d1ccfadefd2d76aa1b5d560058a59b3b849f91be91bf94cf0"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78e3513742a34caece3f6e81b88f50be69a3d5d6"
os = "windows"

    [[DuckDB.download]]
    sha256 = "53a99b4b252a0eea35249352b86ab6c8df4b7ac93771ed00de9861cab6ce75e3"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.4+0/DuckDB.v1.4.4.x86_64-w64-mingw32-cxx11.tar.gz"
