[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "d4038785b0006227dd82c93f8b10181c94102374"
os = "macos"

    [[DuckDB.download]]
    sha256 = "e7662af810ecdcf0b9a17435093db2f0d9b4cf825c8724924a510b5e285b99bd"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "607ce514e30d4be75efc6bbb75d470c62a8173ed"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "8e1c1f5e3fc150e373e1f78661ce367816da062f22ebdaabce4055f80b2ceb7d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb182b4b70db42caef78def44e5b15dd0a531d97"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "496e03146d15319e9a337dd354984fe001aa38670fa0940ee5c3097c1c5af4e9"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "7e6f104b6587f8eed6f111919d61f8708eceda46"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "22f566d30f3343e50fb160d4dbf04fc5d3a82b84f21dac8aac60dd666b02c0d8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4b260198bdd589079e3b6c174e45cf3ce590642"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "830754e0f3ff8b8443c7a245d3b0d81828b1b810eb95c651dcb15ff8289975a5"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcf3a48ec1b717f6a86f5f34b6ffc415dc0cc1ee"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "0fb14ce8ef6b8ba8fc264c50960eb6b49c0ee9cd8019335dfb9ac496bb940359"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35b6b174105bcb0aae1ddd225d5ccae463c81d65"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c99464816c8806bcf1e76793c4bbec004b8d2cabaac8050785fd49784481ed69"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47c90e33950d748a0472daa2bcd9b10f5f40c30e"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "4556af9f476e66581f42e7bab30fda57afcd147370767760eebf5e6ff053430d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74b3b0c1cb40563c96dc784583a727994998bbcf"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "f76895eb7592af97e326905a85e6dfa176a9b4c3f6aec6be43dee14d2fd174dd"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b2cb8405b1f96e7510fa49b58d19edf9825233d"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "8332252eb528491ef4a2bd6a7b9b0ecade9e385d42d514472e9ceac07888579b"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6848ae72390b010d818e2c4a634411661ae01afe"
os = "windows"

    [[DuckDB.download]]
    sha256 = "d7eccc49ea80f31995ea0a6d6f5891328b16ee2751d54217622ad627d33fac90"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f9dd8db3546b6b8e62858bfc4973b69835e5bd"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "2f282e4c063a072405bd46f4a9111253c121e8d3d8453fd5390f4186750d0a4d"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "71a7e694a76deceda56a08d9e364f689e3f1bc1a"
os = "macos"

    [[DuckDB.download]]
    sha256 = "1a6da5b2e9ff8525b4483a4d363651a61fc851bdac73618a67728a3e77c7ba71"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dccd1820215648640ca5733bd1edf104480fd2d7"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "da723573a3e249a7d6352076c9463908720edf462826e14d24b29043ba4d1c28"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d363dd4834e0949167be03b71269b1e89b2c648"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "93ae45325a0a82cefcff26c8d9a8a341f1816a027d6262a481e75518e2ba6a99"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "6f1ffc0e3762219d3e7ec04cb0712d6691ff2783"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "18a1cd3da60f0f2c03959a70ad9e7c1eb3e0913a3e6806058554af88c29ecf57"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ccd958c1a7d2d723ae0e8472492cbe99b5984e6"
os = "windows"

    [[DuckDB.download]]
    sha256 = "eafc33448913e00e69b93bfc595cce2aa8d337e958072b0f25e4ec5a00bd96c3"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.2+0/DuckDB.v1.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
