[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "4093aa4131d0f2bc07dad27c1bb671c04d154bf3"
os = "macos"

    [[DuckDB.download]]
    sha256 = "7cb86ad7e0c8bf93455e9d79bda963b30269d3f75b53465030bf0e293a0ced46"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.aarch64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ed56d71c457714e6c40bd46d3fdd2146c618a9"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "bd44aa7987bb54073890cebc2a3a16c8ee5c8f458d6727e43945cb7f832fef76"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.aarch64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b6fbbe3ae4071fdaed7b4a5438993f82aae1036"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "e1b5f88d49b0ad8f2fe996c4923cd15f3f0b3a30b0455d4e8363abc4237d20b0"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.aarch64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "aarch64"
git-tree-sha1 = "81dd7d3979801d7d2175b5ba94473bb952110a49"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "7754ba027d0dfa0401aa64224afed171cb8668d607adc9d0e5908a1b2d350cdd"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.aarch64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bd2a4ada713c22d168b43fd1950931f35c9bad1"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "8ff8f055f1cb74a303af906a64be62d4dd889c7473baa71efef45d121d90bd27"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdf03bcf45e324c088b8d5a4da46cd77df903b26"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "0982427ce61bdd6f23a4fa48e0ee19114ec9ea2a506b32bdfad095c99a6b2f87"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dbb094cb0a3ccc33a7206a5d0caee2edbe45010"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "6a146c0a3b720e053fe86b2bdd9cea5df0a0b97664e9d9896ac59e274a545953"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4506b2fdf0313b0571fa1a86e438d4a2e5961899"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "ee7c434686a6d77bff29215b639c8e88e459355c97c5bbea6656cc444c46950c"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27779580cb2b04280f28e6b2b51c12a394bda11b"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "c999dc5b1e2d3430be5a38795794eb1ba11da9d988e140bc0a73611f34d8e953"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.i686-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dcf1a6205ecc157ea4b207adf9424e942965d3d"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "b1016ecc987c3226ecca561d653f2570d7a5d42992e17a739c10f7a3ccfc9d31"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.i686-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fad6c211deb39fd2ef0593fae0f48cdd2ae0ab90"
os = "windows"

    [[DuckDB.download]]
    sha256 = "216fc0b04362e2f88896c799e7e0a22e99b9723389e2c781f7dfa223dd43e6c4"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.i686-w64-mingw32-cxx11.tar.gz"
[[DuckDB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40cb51db71175c0fd266c79975ba1cbb93b05462"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "f34abc063b1c2ddce7fc083fcc15544cb6f6e31a97ef95e3f1ceabeab3def960"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.riscv64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "6c5caa7862cc75ce3b5b476cb8c3938e375d7008"
os = "macos"

    [[DuckDB.download]]
    sha256 = "4727524041d1ff28c7c1864af0b7358512945cf08892d03fb6d6102b6be89e0e"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.x86_64-apple-darwin.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48cabd1cd1327f45bc921d5ce92bc0a174341378"
libc = "glibc"
os = "linux"

    [[DuckDB.download]]
    sha256 = "e8926e8f0eddc1a69eb7c457d7e0506571ec7ca49343684fc53082922e144ad8"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.x86_64-linux-gnu-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf07687523fdcf5987d0ea05a108a8679cad1f41"
libc = "musl"
os = "linux"

    [[DuckDB.download]]
    sha256 = "ad50f74cdce746686bffc03eec4dad9181c1c6d4edf843792f7f6f03ae987729"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.x86_64-linux-musl-cxx11.tar.gz"
[[DuckDB]]
arch = "x86_64"
git-tree-sha1 = "1d51be64b248b978ee4680878022f5871cc6cf06"
os = "freebsd"

    [[DuckDB.download]]
    sha256 = "e587b02266c3212cb450198dff0a5b10ee4014fba3413e9dd1557f8096da4d1e"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.x86_64-unknown-freebsd.tar.gz"
[[DuckDB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f4df99c777cbc8db22f231fd936374baba1511e"
os = "windows"

    [[DuckDB.download]]
    sha256 = "c78641123480733e3948c24a0014227a589bba879183636a0341e91c1a20c6dc"
    url = "https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases/download/DuckDB-v1.4.3+0/DuckDB.v1.4.3.x86_64-w64-mingw32-cxx11.tar.gz"
